freetime_advisor:
    resource: "@FreetimeAdvisorBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
# 
# new_advice:
#     resource: "@FreetimeAdvisorBundle/Controller/AdviceController.php"
#     type:     annotation
#     prefix:   /new/advice
