freetime_advisor:
    resource: "@FreetimeAdvisorBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
# 
# fos_user_registration_confirmed:
#     pattern: /registration/confirmed
#     defaults: { _controller: MDBUserBundle:User:confirmed }
#     requirements:
#         _method: GET
#
# new_advice:
#     resource: "@FreetimeAdvisorBundle/Controller/AdviceController.php"
#     type:     annotation
#     prefix:   /new/advice
