freetime_advisor:
    resource: "@FreetimeAdvisorBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# register_categories:
#     resource: "@FreetimeAdvisorBundle/Controller/CategoryController"
#     type:     annotation
#     prefix:   /
