<?php

namespace FreetimeAdvisorBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
* AdviceRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class AdviceRepository extends \Doctrine\ORM\EntityRepository
{
  public function checkIfUserAlreadyPost()
  {
    return $this->getEntityManager()
    ->createQuery(
      'SELECT a FROM FreetimeAdvisorBundle:Advice a ORDER BY a.title ASC'
      )
      ->getResult();
    }

    public function placeAverageScore($place)
    {
      $q = $this->createQueryBuilder('a')
      ->select("avg(a.score) as score, count(a.score) as total")
      ->where('a.place = :place_id')
      ->setParameter('place_id', $place)
      ->setMaxResults(1)
      ->getQuery()
      ->getSingleResult();

      return $q;
    }

    public function allPlaceAverageScore()
    {
      $q = $this->createQueryBuilder('a')
      ->select("IDENTITY(a.place) as place_id,avg(a.score) as score, count(a.score) as total")
      ->groupBy('place_id')
      ->getQuery()
      ->getResult();

      return $q;
    }
  }
