<?php

namespace FreetimeAdvisorBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * AdviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdviceRepository extends \Doctrine\ORM\EntityRepository
{
  public function checkIfUserAlreadyPost()
  {
    return $this->getEntityManager()
        ->createQuery(
            'SELECT a FROM FreetimeAdvisorBundle:Advice a ORDER BY a.title ASC'
        )
        ->getResult();
    }
}
