<?php

namespace FreetimeAdvisorBundle\Repository;

/**
 * HobbiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HobbiesListRepository extends \Doctrine\ORM\EntityRepository
{
}
