<?php

namespace FreetimeAdvisorBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
* PlaceRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{
  public function findLastPlace()
  {
    $builder = $this->createQueryBuilder('p');
    $q = $builder
    ->andWhere(
      $builder->expr()->isNotNull('p.date'))
    ->getQuery();

      return $q->getResult();
    }
  }
